angular.module('myTranslate',['pascalprecht.translate'])
.config(function($translateProvider){
	$translateProvider.translations('en',{
		title: 'BREAKING NEWS',
		latest :'LATEST',
		feature :'FEATURE',
		video :'VIDEO',
		photo :'PHOTO',
		dayago:'days ago',
		bookmark :'BookMark',
		bookmarks :'BookMarks',
		bookmarkimage: 'Bookmark Image',
		unbookmarkimage: 'Unbookmark Image',
		titleComment: '',
		by: 'by',
		thisis: 'THIS ARTICLE HAS',
		
		textsize :'TextSize',
		pushnotification:'Push Notification',
		notification: 'Notification',
		currently: 'There are currently no notification',
		share :'Share',
		Stories: 'Top Stories',
		comment: 'Comments',
		dailybreif: 'Daily Breif',
		Magazine: 'Magazine Update',
		help :'Help',
		pickalert: 'Pick Your Alert',
		brekingnews: 'BreakingNew, special report and editor picks',
		twiceaday: 'Twice a day,Morning and Evening',
		RememberThisChoice: 'Remember This Choice',
		small: 'Small',
		normal: 'Normal',
		large:'Large',
		extralager: 'Extra Large',
		logout:'Log Out',
		login :'Log In',
		noaccount: 'No account yet? Create one',
		category:'Categories',
		
		search :'Search',
		newEmail: 'New Email',
		currentPassword: 'Current Password',
		confirmPass: 'Confirm Password',
		changepass: 'Change Passwords',
		changemail: 'Change Email',
		emailInvalid: 'Email Invalid',
		usernameInvalid: 'Username Invalid',
		update:'UPDATE',
		for:'for',
		username: 'Username',
		Email: 'Email',
		charactor: 'at least 4 characters',
		namevalid:'Name Invalid',
		member: 'Already a memeber? Login',
		signup:'Sign Up',
		pass: 'Password',
		name: 'Name',
		enterusername: 'Enter your username',
		enteremail: 'Enter your email',
		enterpass: 'Enter your password',
		
		forgotPassWord: 'Forgot PassWord?',
		noResults :'No Result Availbles',
		keyword: 'Keyword is required',
		news :'News',
		slide: 'START SLIDESHOW',
		faq: 'FAQs',
		time:'Time',
		term: 'Terms And Conditions',
		rateapp: 'Terms And Conditions',
		remove :'Remove',
		addcomment :'Add a comment',
		profile :'Profile',
		fullname :'Full Name',
		confirmfoforgot: 'Enter your email adress associated with your account & we will shall your link to reset password',
		save: 'SAVE',
		emailInvalid: 'Email Invalid',
		resetLink: 'SEND RESET LINK',
		passwordInvalid: 'Password Invalid',
		changeEmail: 'Change Email?',
		change :'CHANGE',
		recentSearch: 'RECENT SEARCHES',
		clear: 'Clear',
		forgot:'Forgot',
		sucess :'Sucessfully',
		removed :'Removed',
		signup :'Sign Up',
		signin :'Sign In',
		forgot :'forgot',
		nobookmark: 'No Bookmarks'
	});
	$translateProvider.useSanitizeValueStrategy('escapeParameters');
	$translateProvider.preferredLanguage("en");
	$translateProvider.fallbackLanguage("en");
});